### ISSUE TITLE
Agreed Work to address standards 2019-01-29

### ISSUE THREAD

**Issue by maryfries** [bjc-edc-2017-18/bjc-r#38]
- [x] [Replace 1.2.4 with who2](http://localhost/bjc-r/cur/programming/1-introduction/2-gossip-and-greet/4-learning-names.html?topic=nyc_bjc%2F1-intro-loops.topic&course=bjc4nyc.html&novideo&noassignment)
- [x] Making [Modeling Language](https://github.com/bjc-edc-2017-18/bjc-r/issues/22) a U1 optional project
- [ ] Dropping [2.1.4](http://localhost/bjc-r/cur/programming/2-complexity/1-variables-games/4-importing-exporting.html?topic=nyc_bjc%2F2-conditionals-abstraction.topic&course=bjc4nyc.html&novideo&noassignment) (done) and integrating “importing” into [2.3.2](http://localhost/bjc-r/cur/programming/2-complexity/3-predicates/2-keeping-list-items.html?topic=nyc_bjc%2F2-conditionals-abstraction.topic&course=bjc4nyc.html&novideo&noassignment) (not done)
- [x] Adding to-be-developed ADT Quizlets to 2.2
- [x] Adding [Shopping List](http://localhost/bjc-r/cur/programming/2-complexity/2-data-structures-art/1-shopping-list-app.html?topic=nyc_bjc%2F2-conditionals-abstraction.topic&course=bjc4nyc.html&novideo&noassignment) back in 2.4 (now slated for [2.2](https://github.com/bjc-edc-2017-18/bjc-r/issues/39))
- [ ] Adding [birthdate](http://localhost/bjc-r/cur/programming/3-lists/1-introduction-to-lists/unused-new-stuff/4-modifying-adt.html) into 3.1
- [ ] [U3 Data Processing & U2 Data and MathTools Plan](https://github.com/bjc-edc-2017-18/bjc-r/issues/36)
- [x] Dropping [5.2.2](http://localhost/bjc-r/cur/programming/5-algorithms/2-simulation/2-flipping-a-coin.html?topic=nyc_bjc%2F5-algorithms.topic&course=bjc4nyc.html&novideo&noassignment)

**Comment by maryfries** [comment]
UPDATE: Shopping List is now slated for [2.2](https://github.com/bjc-edc-2017-18/bjc-r/issues/39)

**Comment by maryfries** [comment]
Next steps:
- [ ] Mary to clean up 2.1 TG after (pg 1 split in two and pg 4 dropped)

**Comment by maryfries** [comment]
Additional things to do (that have not been agreed on with whole team):
- [ ] revise 5.4 (Unsolvable and Undecidable Problems)
